### ISSUE TITLE
ModuleNotFoundError: No module named 'simclr'

### ISSUE THREAD

**Issue by Open-Debin** [ebadrian/metadl#2]
the error happened at from meta_dataset.data import pipeline
/meta-dataset/meta_dataset/data/pipeline.py in <module>
     39 from meta_dataset.data import reader
     40 from meta_dataset.data import sampling
---> 41 from simclr import data_util
     42 from six.moves import zip
     43 import tensorflow.compat.v1 as tf

ModuleNotFoundError: No module named 'simclr

Please tell me how can I fix it.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Open-Debin** [comment]
the error happened at file starting_kit/tutorial.ipynb

**Comment by ebadrian** [comment]
Hi Open-Debin!
The issue was occurring only for conda environments. The problem has been solved, you need to pull the changes though. Also, you will need to remove the previous **metadl** conda environment, using this command :
```bash
conda env remove --name metadl
```
Once these 2 steps are done, you can re-launch the quick_start.sh script and follow the described instructions.

I am closing the issue, feel free to re-open one if necessary.
