### ISSUE TITLE
Not installing meta-dataset package

### ISSUE THREAD

**Issue by MichaelMMeskhi** [ebadrian/metadl#7]
**Describe the bug**
The script `quick_start.sh` is supposed to install meta-dataset. Unfortunately, that does not happen for some reason. I just wanted to double-check this.

**To Reproduce**
1. Run `quick_start.sh`
2. Run the first code block in Jupyter notebook

**Expected behavior**
Expected to have meta-dataset installed.

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: macOS 15.11
 - Browser: Safari

**Comment by ebadrian** [comment]
Hello Michael! 
I couldn't reproduce your error, it's probably due to one of the following problems though, could you please check that: 

1) that you have run the quick_start.sh file under the neurips2021 branch. In order to check that, simply type `git branch` in the metadl repository. 
2) that you have activated the metadl conda environment before launching the jupyter notebook.

Let me know how it goes!
